### ISSUE TITLE
Flip option for tate mode

### ISSUE THREAD

**Issue by x0rtrunks** [MiSTer-devel/AtariLynx_MiSTer#7] opened 2021-03-20 05:02 UTC
My monitor only rotates in one direction, so when playing a game like Raiden it only goes into tate mode (ie horz) upside down. A flip option would be great! Thanks for the core.

**Comment by RobertPeip** [comment] 2021-03-20 06:38
duplicate of this: https://github.com/MiSTer-devel/AtariLynx_MiSTer/issues/4

**Closed as completed by RobertPeip** 2021-03-20 06:38 UTC
